name: ehr-datasets-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core Data Science
  - numpy=1.21.*
  - pandas=1.3.*
  - scikit-learn=1.0.*
  - scipy=1.7.*
  
  # Visualization
  - matplotlib=3.5.*
  - seaborn=0.11.*
  - plotly=5.0.*
  
  # Time Series
  - statsmodels=0.13.*
  
  # Deep Learning with CUDA
  - pytorch=1.12.*
  - torchvision=0.13.*
  - pytorch-cuda=11.6  # For CUDA 11.6
  # Alternative CUDA versions:
  # - pytorch-cuda=11.7  # For CUDA 11.7
  # - pytorch-cuda=11.8  # For CUDA 11.8
  
  # Jupyter
  - jupyter=1.0.*
  - jupyterlab=3.4.*
  - ipykernel=6.15.*
  - notebook=6.4.*
  
  # Utilities
  - tqdm=4.64.*
  - joblib=1.1.*
  - pyyaml=6.0.*
  - h5py=3.7.*
  - openpyxl=3.0.*
  
  # Pip dependencies (install via pip)
  - pip
  - pip:
    # Transformers and advanced ML
    - transformers>=4.20.0
    - pytorch-lightning>=1.7.0
    - darts>=0.20.0
    - gluonts>=0.11.0
    - tslearn>=0.5.0
    
    # Tabular ML
    - catboost>=1.1.0
    - xgboost>=1.6.0
    - lightgbm>=3.3.0
    
    # Medical/Healthcare
    - lifelines>=0.27.0
    - imbalanced-learn>=0.9.0
    
    # Configuration
    - python-dotenv>=0.19.0
    - pathlib2>=2.3.0
    
    # GPU acceleration
    - cupy-cuda11x>=10.6.0


